# Generated by Django 4.2.7 on 2025-11-06 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lead_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('project_name', models.CharField(blank=True, choices=[('Altura', 'Altura'), ('Beachgate by Address', 'Beachgate by Address'), ('Damac Bay by Cavalli', 'Damac Bay by Cavalli'), ('DLF West Park', 'DLF West Park'), ('Godrej Vistas', 'Godrej Vistas'), ('Lumina Grand', 'Lumina Grand'), ('Sobha Crest', 'Sobha Crest'), ('Sobha Waves', 'Sobha Waves')], max_length=100, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('studio', 'Studio'), ('1 bed', '1 Bed'), ('2 bed', '2 Bed'), ('2 bed w study', '2 bed w study'), ('3 bed', '3 bed'), ('4 bed', '4 bed'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse')], max_length=50, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lead_status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('visit_scheduled', 'Visit scheduled'), ('visit_done_not_purchased', 'Visit done not purchased'), ('purchased', 'Purchased'), ('not_interested', 'Not interested')], default='not_connected', max_length=50)),
                ('last_conversation_date', models.DateField(blank=True, null=True)),
                ('last_conversation_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_leads',
                'ordering': ['-last_conversation_date', '-created_at'],
                'indexes': [models.Index(fields=['lead_status'], name='crm_leads_lead_st_c7e6db_idx'), models.Index(fields=['project_name'], name='crm_leads_project_613737_idx'), models.Index(fields=['unit_type'], name='crm_leads_unit_ty_fe9195_idx'), models.Index(fields=['last_conversation_date'], name='crm_leads_last_co_eebf86_idx')],
            },
        ),
    ]
