# Generated by Django 4.2.7 on 2025-11-06 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_project_name', models.CharField(choices=[('Altura', 'Altura'), ('Beachgate by Address', 'Beachgate by Address'), ('Damac Bay by Cavalli', 'Damac Bay by Cavalli'), ('DLF West Park', 'DLF West Park'), ('Godrej Vistas', 'Godrej Vistas'), ('Lumina Grand', 'Lumina Grand'), ('Sobha Crest', 'Sobha Crest'), ('Sobha Waves', 'Sobha Waves')], max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('sales_offer_details', models.TextField(blank=True, null=True)),
                ('filter_project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('filter_unit_types', models.JSONField(blank=True, default=list)),
                ('filter_min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filter_max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filter_lead_status', models.CharField(blank=True, max_length=50, null=True)),
                ('filter_date_from', models.DateField(blank=True, null=True)),
                ('filter_date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to='crm.lead')),
            ],
            options={
                'db_table': 'campaign_messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalized_message', models.TextField(blank=True, null=True)),
                ('message_sent_at', models.DateTimeField(blank=True, null=True)),
                ('goal_achieved', models.BooleanField(default=False)),
                ('goal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('goal_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sales_associate_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
            options={
                'db_table': 'campaign_leads',
                'unique_together': {('campaign', 'lead')},
            },
        ),
        migrations.CreateModel(
            name='CampaignConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_message', models.TextField()),
                ('agent_response', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='crm.lead')),
            ],
            options={
                'db_table': 'campaign_conversations',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignLead', to='crm.lead'),
        ),
    ]


