# Generated by Django 4.2.7 on 2025-11-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='goal_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='goal_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
