# Generated by Django 4.2.7 on 2025-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignlead_goal_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
